// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cert/certid/v1/certid.proto

package types

import (
	fmt "fmt"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CertID defines the profile structure
type CertID struct {
	Address           string            `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Handle            string            `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Name              string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bio               string            `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarCID         string            `protobuf:"bytes,5,opt,name=avatar_cid,json=avatarCid,proto3" json:"avatar_cid,omitempty"`
	MetadataURI       string            `protobuf:"bytes,6,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	AttestationUID    string            `protobuf:"bytes,7,opt,name=attestation_uid,json=attestationUid,proto3" json:"attestation_uid,omitempty"`
	PublicKey         string            `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	EntityType        uint32            `protobuf:"varint,9,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	TrustScore        uint64            `protobuf:"varint,10,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	SocialLinks       map[string]string `protobuf:"bytes,11,rep,name=social_links,json=socialLinks,proto3" json:"social_links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Credentials       []string          `protobuf:"bytes,12,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Badges            map[string]*Badge `protobuf:"bytes,13,rep,name=badges,proto3" json:"badges,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt         time.Time         `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	UpdatedAt         time.Time         `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	Verified          bool              `protobuf:"varint,16,opt,name=verified,proto3" json:"verified,omitempty"`
	IsActive          bool              `protobuf:"varint,17,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	VerificationLevel uint32            `protobuf:"varint,18,opt,name=verification_level,json=verificationLevel,proto3" json:"verification_level,omitempty"`
}

func (m *CertID) Reset()         { *m = CertID{} }
func (m *CertID) String() string { return proto.CompactTextString(m) }
func (*CertID) ProtoMessage()    {}
func (*CertID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b291f1bfd397e965, []int{0}
}
func (m *CertID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CertID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CertID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CertID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertID.Merge(m, src)
}
func (m *CertID) XXX_Size() int {
	return m.Size()
}
func (m *CertID) XXX_DiscardUnknown() {
	xxx_messageInfo_CertID.DiscardUnknown(m)
}

var xxx_messageInfo_CertID proto.InternalMessageInfo

func (m *CertID) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CertID) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *CertID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CertID) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *CertID) GetAvatarCID() string {
	if m != nil {
		return m.AvatarCID
	}
	return ""
}

func (m *CertID) GetMetadataURI() string {
	if m != nil {
		return m.MetadataURI
	}
	return ""
}

func (m *CertID) GetAttestationUID() string {
	if m != nil {
		return m.AttestationUID
	}
	return ""
}

func (m *CertID) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *CertID) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *CertID) GetTrustScore() uint64 {
	if m != nil {
		return m.TrustScore
	}
	return 0
}

func (m *CertID) GetSocialLinks() map[string]string {
	if m != nil {
		return m.SocialLinks
	}
	return nil
}

func (m *CertID) GetCredentials() []string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *CertID) GetBadges() map[string]*Badge {
	if m != nil {
		return m.Badges
	}
	return nil
}

func (m *CertID) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *CertID) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *CertID) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *CertID) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *CertID) GetVerificationLevel() uint32 {
	if m != nil {
		return m.VerificationLevel
	}
	return 0
}

// Badge defines a soulbound token
type Badge struct {
	ID          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AwardedAt   time.Time  `protobuf:"bytes,4,opt,name=awarded_at,json=awardedAt,proto3,stdtime" json:"awarded_at"`
	AwardedBy   string     `protobuf:"bytes,5,opt,name=awarded_by,json=awardedBy,proto3" json:"awarded_by,omitempty"`
	IsRevoked   bool       `protobuf:"varint,6,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	RevokedAt   *time.Time `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3,stdtime" json:"revoked_at,omitempty"`
}

func (m *Badge) Reset()         { *m = Badge{} }
func (m *Badge) String() string { return proto.CompactTextString(m) }
func (*Badge) ProtoMessage()    {}
func (*Badge) Descriptor() ([]byte, []int) {
	return fileDescriptor_b291f1bfd397e965, []int{1}
}
func (m *Badge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Badge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Badge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Badge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Badge.Merge(m, src)
}
func (m *Badge) XXX_Size() int {
	return m.Size()
}
func (m *Badge) XXX_DiscardUnknown() {
	xxx_messageInfo_Badge.DiscardUnknown(m)
}

var xxx_messageInfo_Badge proto.InternalMessageInfo

func (m *Badge) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Badge) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Badge) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Badge) GetAwardedAt() time.Time {
	if m != nil {
		return m.AwardedAt
	}
	return time.Time{}
}

func (m *Badge) GetAwardedBy() string {
	if m != nil {
		return m.AwardedBy
	}
	return ""
}

func (m *Badge) GetIsRevoked() bool {
	if m != nil {
		return m.IsRevoked
	}
	return false
}

func (m *Badge) GetRevokedAt() *time.Time {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

// Params defines the module parameters
type Params struct {
	MaxUsernameLength    uint32      `protobuf:"varint,1,opt,name=max_username_length,json=maxUsernameLength,proto3" json:"max_username_length,omitempty"`
	MaxDisplayNameLength uint32      `protobuf:"varint,2,opt,name=max_display_name_length,json=maxDisplayNameLength,proto3" json:"max_display_name_length,omitempty"`
	MaxBioLength         uint32      `protobuf:"varint,3,opt,name=max_bio_length,json=maxBioLength,proto3" json:"max_bio_length,omitempty"`
	MaxCredentials       uint32      `protobuf:"varint,4,opt,name=max_credentials,json=maxCredentials,proto3" json:"max_credentials,omitempty"`
	RegistrationFee      types1.Coin `protobuf:"bytes,5,opt,name=registration_fee,json=registrationFee,proto3" json:"registration_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b291f1bfd397e965, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxUsernameLength() uint32 {
	if m != nil {
		return m.MaxUsernameLength
	}
	return 0
}

func (m *Params) GetMaxDisplayNameLength() uint32 {
	if m != nil {
		return m.MaxDisplayNameLength
	}
	return 0
}

func (m *Params) GetMaxBioLength() uint32 {
	if m != nil {
		return m.MaxBioLength
	}
	return 0
}

func (m *Params) GetMaxCredentials() uint32 {
	if m != nil {
		return m.MaxCredentials
	}
	return 0
}

func (m *Params) GetRegistrationFee() types1.Coin {
	if m != nil {
		return m.RegistrationFee
	}
	return types1.Coin{}
}

func init() {
	proto.RegisterType((*CertID)(nil), "cert.certid.v1.CertID")
	proto.RegisterMapType((map[string]*Badge)(nil), "cert.certid.v1.CertID.BadgesEntry")
	proto.RegisterMapType((map[string]string)(nil), "cert.certid.v1.CertID.SocialLinksEntry")
	proto.RegisterType((*Badge)(nil), "cert.certid.v1.Badge")
	proto.RegisterType((*Params)(nil), "cert.certid.v1.Params")
}

func init() { proto.RegisterFile("cert/certid/v1/certid.proto", fileDescriptor_b291f1bfd397e965) }

var fileDescriptor_b291f1bfd397e965 = []byte{
	// 901 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0x23, 0xb5,
	0x1b, 0xef, 0x24, 0x69, 0x9a, 0x3c, 0xd3, 0x26, 0xad, 0xff, 0xfd, 0x2f, 0x43, 0x56, 0x24, 0x51,
	0x85, 0xb4, 0x91, 0x58, 0x66, 0xd4, 0x20, 0x24, 0xb4, 0x48, 0xa0, 0xbc, 0xb0, 0x52, 0x96, 0x82,
	0x56, 0xb3, 0x9b, 0x0b, 0x97, 0x91, 0x67, 0xec, 0xa6, 0x56, 0xe7, 0x25, 0xb2, 0x9d, 0x90, 0xf9,
	0x0a, 0x1c, 0xd0, 0x5e, 0xf9, 0x46, 0x7b, 0xdc, 0x23, 0xa7, 0x80, 0xd2, 0x2f, 0x82, 0x6c, 0x4f,
	0xda, 0x61, 0x05, 0x42, 0x7b, 0x89, 0xfc, 0xfc, 0x5e, 0x6c, 0xe7, 0x79, 0xf1, 0xc0, 0xe3, 0x88,
	0x72, 0xe9, 0xa9, 0x1f, 0x46, 0xbc, 0xf5, 0x65, 0xb1, 0x72, 0x97, 0x3c, 0x93, 0x19, 0x6a, 0xa9,
	0xc8, 0x2d, 0xa0, 0xf5, 0x65, 0xe7, 0x7c, 0x91, 0x2d, 0x32, 0x4d, 0x79, 0x6a, 0x65, 0x54, 0x9d,
	0xde, 0x22, 0xcb, 0x16, 0x31, 0xf5, 0x74, 0x14, 0xae, 0xae, 0x3d, 0xc9, 0x12, 0x2a, 0x24, 0x4e,
	0x96, 0x85, 0xa0, 0x1b, 0x65, 0x22, 0xc9, 0x84, 0x17, 0x62, 0x41, 0xbd, 0xf5, 0x65, 0x48, 0x25,
	0xbe, 0xf4, 0xa2, 0x8c, 0xa5, 0x86, 0xbf, 0xf8, 0xf5, 0x08, 0xea, 0x13, 0xca, 0xe5, 0x6c, 0x8a,
	0x1c, 0x38, 0xc2, 0x84, 0x70, 0x2a, 0x84, 0x63, 0xf5, 0xad, 0x41, 0xd3, 0xdf, 0x87, 0xe8, 0x11,
	0xd4, 0x6f, 0x70, 0x4a, 0x62, 0xea, 0x54, 0x34, 0x51, 0x44, 0x08, 0x41, 0x2d, 0xc5, 0x09, 0x75,
	0xaa, 0x1a, 0xd5, 0x6b, 0x74, 0x0a, 0xd5, 0x90, 0x65, 0x4e, 0x4d, 0x43, 0x6a, 0x89, 0x9e, 0x02,
	0xe0, 0x35, 0x96, 0x98, 0x07, 0x11, 0x23, 0xce, 0xa1, 0x22, 0xc6, 0x27, 0xbb, 0x6d, 0xaf, 0x39,
	0xd2, 0xe8, 0x64, 0x36, 0xf5, 0x9b, 0x46, 0x30, 0x61, 0x04, 0x0d, 0xe1, 0x38, 0xa1, 0x12, 0x13,
	0x2c, 0x71, 0xb0, 0xe2, 0xcc, 0xa9, 0x6b, 0x7d, 0x7b, 0xb7, 0xed, 0xd9, 0x3f, 0x14, 0xf8, 0xdc,
	0x9f, 0xf9, 0xf6, 0x5e, 0x34, 0xe7, 0x0c, 0x7d, 0x0d, 0x6d, 0x2c, 0xa5, 0xfa, 0xdf, 0x92, 0x65,
	0x69, 0xb0, 0x62, 0xc4, 0x39, 0xd2, 0x36, 0xb4, 0xdb, 0xf6, 0x5a, 0xa3, 0x07, 0x6a, 0x3e, 0x9b,
	0xfa, 0xad, 0x92, 0x74, 0xce, 0x08, 0xfa, 0x04, 0x60, 0xb9, 0x0a, 0x63, 0x16, 0x05, 0xb7, 0x34,
	0x77, 0x1a, 0xfa, 0xde, 0x4d, 0x83, 0x7c, 0x4f, 0x73, 0xd4, 0x03, 0x9b, 0xa6, 0x92, 0xc9, 0x3c,
	0x90, 0xf9, 0x92, 0x3a, 0xcd, 0xbe, 0x35, 0x38, 0xf1, 0xc1, 0x40, 0xaf, 0xf3, 0x25, 0x55, 0x02,
	0xc9, 0x57, 0x42, 0x06, 0x22, 0xca, 0x38, 0x75, 0xa0, 0x6f, 0x0d, 0x6a, 0x3e, 0x68, 0xe8, 0x95,
	0x42, 0xd0, 0x0b, 0x38, 0x16, 0x59, 0xc4, 0x70, 0x1c, 0xc4, 0x2c, 0xbd, 0x15, 0x8e, 0xdd, 0xaf,
	0x0e, 0xec, 0xe1, 0x13, 0xf7, 0xef, 0x05, 0x76, 0x4d, 0x15, 0xdc, 0x57, 0x5a, 0x7a, 0xa5, 0x94,
	0xdf, 0xa5, 0x92, 0xe7, 0xbe, 0x2d, 0x1e, 0x10, 0xd4, 0x07, 0x3b, 0xe2, 0x94, 0xa8, 0xe3, 0x71,
	0x2c, 0x9c, 0xe3, 0x7e, 0x75, 0xd0, 0xf4, 0xcb, 0x10, 0x7a, 0x06, 0xf5, 0x10, 0x93, 0x05, 0x15,
	0xce, 0x89, 0x3e, 0xe7, 0xe2, 0x5f, 0xce, 0x19, 0x6b, 0x91, 0x39, 0xa2, 0x70, 0xa0, 0x09, 0x40,
	0xc4, 0x29, 0x96, 0x94, 0x04, 0x58, 0x3a, 0xad, 0xbe, 0x35, 0xb0, 0x87, 0x1d, 0xd7, 0xb4, 0x98,
	0xbb, 0x6f, 0x31, 0xf7, 0xf5, 0xbe, 0xc5, 0xc6, 0x8d, 0xb7, 0xdb, 0xde, 0xc1, 0x9b, 0x3f, 0x7a,
	0x96, 0xdf, 0x2c, 0x7c, 0x23, 0xa9, 0x36, 0x59, 0x2d, 0xc9, 0x7e, 0x93, 0xf6, 0x87, 0x6c, 0x52,
	0xf8, 0x46, 0x12, 0x75, 0xa0, 0xb1, 0xa6, 0x9c, 0x5d, 0x33, 0x4a, 0x9c, 0xd3, 0xbe, 0x35, 0x68,
	0xf8, 0xf7, 0x31, 0x7a, 0x0c, 0x4d, 0x26, 0x02, 0x1c, 0x49, 0xb6, 0xa6, 0xce, 0x99, 0x21, 0x99,
	0x18, 0xe9, 0x18, 0x7d, 0x0e, 0xc8, 0x08, 0x23, 0xd3, 0x0b, 0x31, 0x5d, 0xd3, 0xd8, 0x41, 0xba,
	0x6a, 0x67, 0x65, 0xe6, 0x4a, 0x11, 0x9d, 0x6f, 0xe0, 0xf4, 0xfd, 0x84, 0xab, 0x0e, 0x56, 0x9d,
	0x60, 0x66, 0x40, 0x2d, 0xd1, 0x39, 0x1c, 0xae, 0x71, 0xbc, 0xda, 0xb7, 0xbf, 0x09, 0x9e, 0x55,
	0xbe, 0xb2, 0x3a, 0x2f, 0xc1, 0x2e, 0x25, 0xf2, 0x1f, 0xac, 0x9f, 0x95, 0xad, 0xf6, 0xf0, 0xff,
	0xef, 0x57, 0x43, 0xbb, 0x4b, 0x3b, 0x5e, 0xfc, 0x56, 0x81, 0x43, 0x0d, 0xa2, 0x47, 0x50, 0x61,
	0xc4, 0xec, 0x35, 0xae, 0xef, 0xb6, 0xbd, 0xca, 0x6c, 0xea, 0x57, 0x18, 0xb9, 0x9f, 0xba, 0x4a,
	0x69, 0xea, 0xfa, 0x60, 0x13, 0x2a, 0x22, 0xce, 0x96, 0xea, 0xbf, 0x15, 0x03, 0x59, 0x86, 0x54,
	0x59, 0xf0, 0xcf, 0x98, 0x13, 0x53, 0x96, 0xda, 0x87, 0x94, 0xa5, 0xf0, 0x8d, 0xa4, 0x9a, 0x95,
	0xfd, 0x26, 0x61, 0x6e, 0x46, 0xf9, 0x9e, 0x1e, 0xe7, 0x8a, 0x66, 0x22, 0xe0, 0x74, 0x9d, 0xdd,
	0x52, 0xa2, 0x27, 0xb7, 0xe1, 0x37, 0x99, 0xf0, 0x0d, 0x80, 0xbe, 0x05, 0x28, 0x38, 0x75, 0x85,
	0xa3, 0xff, 0xbc, 0x42, 0xcd, 0x1c, 0x5f, 0x78, 0x46, 0xf2, 0xe2, 0x97, 0x0a, 0xd4, 0x5f, 0x62,
	0x8e, 0x13, 0x81, 0x5c, 0xf8, 0x5f, 0x82, 0x37, 0xc1, 0x4a, 0x50, 0xae, 0x12, 0x10, 0xc4, 0x34,
	0x5d, 0xc8, 0x1b, 0x9d, 0xad, 0x13, 0xff, 0x2c, 0xc1, 0x9b, 0x79, 0xc1, 0x5c, 0x69, 0x02, 0x7d,
	0x09, 0x1f, 0x29, 0x3d, 0x61, 0x62, 0x19, 0xe3, 0x3c, 0x28, 0x7b, 0x2a, 0xda, 0x73, 0x9e, 0xe0,
	0xcd, 0xd4, 0xb0, 0x3f, 0x3e, 0xd8, 0x3e, 0x85, 0x96, 0xb2, 0x85, 0x2c, 0xdb, 0xab, 0xab, 0x5a,
	0x7d, 0x9c, 0xe0, 0xcd, 0x98, 0x65, 0x85, 0xea, 0x09, 0xb4, 0x95, 0xaa, 0x3c, 0x99, 0x35, 0x2d,
	0x53, 0xe6, 0x49, 0x69, 0x38, 0x5f, 0xc0, 0x29, 0xa7, 0x0b, 0x26, 0x24, 0x37, 0xdd, 0x79, 0x4d,
	0xa9, 0xce, 0xa2, 0x3d, 0xfc, 0xd8, 0x35, 0x0f, 0xb5, 0xab, 0x1e, 0x6a, 0xb7, 0x78, 0xa8, 0xdd,
	0x49, 0xc6, 0xd2, 0x71, 0x4d, 0x55, 0xc2, 0x6f, 0x97, 0x8d, 0xcf, 0x29, 0x1d, 0x3f, 0x7f, 0xbb,
	0xeb, 0x5a, 0xef, 0x76, 0x5d, 0xeb, 0xcf, 0x5d, 0xd7, 0x7a, 0x73, 0xd7, 0x3d, 0x78, 0x77, 0xd7,
	0x3d, 0xf8, 0xfd, 0xae, 0x7b, 0xf0, 0xd3, 0xd3, 0x05, 0x93, 0x37, 0xab, 0xd0, 0x8d, 0xb2, 0xc4,
	0x8b, 0x6e, 0x30, 0x4b, 0x75, 0xbb, 0x5d, 0xe7, 0xfa, 0x03, 0x43, 0xbc, 0xcd, 0xfe, 0x93, 0xa3,
	0x1e, 0x34, 0x11, 0xd6, 0x75, 0xe6, 0xbf, 0xf8, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x81, 0x47, 0x50,
	0xc8, 0x8e, 0x06, 0x00, 0x00,
}

func (m *CertID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CertID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerificationLevel != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.VerificationLevel))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCertid(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x7a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintCertid(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x72
	if len(m.Badges) > 0 {
		for k := range m.Badges {
			v := m.Badges[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintCertid(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCertid(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCertid(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.Credentials) > 0 {
		for iNdEx := len(m.Credentials) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Credentials[iNdEx])
			copy(dAtA[i:], m.Credentials[iNdEx])
			i = encodeVarintCertid(dAtA, i, uint64(len(m.Credentials[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.SocialLinks) > 0 {
		for k := range m.SocialLinks {
			v := m.SocialLinks[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintCertid(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCertid(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCertid(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.TrustScore != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.TrustScore))
		i--
		dAtA[i] = 0x50
	}
	if m.EntityType != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.EntityType))
		i--
		dAtA[i] = 0x48
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AttestationUID) > 0 {
		i -= len(m.AttestationUID)
		copy(dAtA[i:], m.AttestationUID)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.AttestationUID)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MetadataURI) > 0 {
		i -= len(m.MetadataURI)
		copy(dAtA[i:], m.MetadataURI)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.MetadataURI)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AvatarCID) > 0 {
		i -= len(m.AvatarCID)
		copy(dAtA[i:], m.AvatarCID)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.AvatarCID)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Bio) > 0 {
		i -= len(m.Bio)
		copy(dAtA[i:], m.Bio)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.Bio)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Handle) > 0 {
		i -= len(m.Handle)
		copy(dAtA[i:], m.Handle)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.Handle)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Badge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Badge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Badge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevokedAt != nil {
		n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.RevokedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintCertid(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x3a
	}
	if m.IsRevoked {
		i--
		if m.IsRevoked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.AwardedBy) > 0 {
		i -= len(m.AwardedBy)
		copy(dAtA[i:], m.AwardedBy)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.AwardedBy)))
		i--
		dAtA[i] = 0x2a
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.AwardedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AwardedAt):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintCertid(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x22
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintCertid(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RegistrationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCertid(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MaxCredentials != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.MaxCredentials))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxBioLength != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.MaxBioLength))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxDisplayNameLength != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.MaxDisplayNameLength))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxUsernameLength != 0 {
		i = encodeVarintCertid(dAtA, i, uint64(m.MaxUsernameLength))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCertid(dAtA []byte, offset int, v uint64) int {
	offset -= sovCertid(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CertID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.Handle)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.Bio)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.AvatarCID)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.MetadataURI)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.AttestationUID)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	if m.EntityType != 0 {
		n += 1 + sovCertid(uint64(m.EntityType))
	}
	if m.TrustScore != 0 {
		n += 1 + sovCertid(uint64(m.TrustScore))
	}
	if len(m.SocialLinks) > 0 {
		for k, v := range m.SocialLinks {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCertid(uint64(len(k))) + 1 + len(v) + sovCertid(uint64(len(v)))
			n += mapEntrySize + 1 + sovCertid(uint64(mapEntrySize))
		}
	}
	if len(m.Credentials) > 0 {
		for _, s := range m.Credentials {
			l = len(s)
			n += 1 + l + sovCertid(uint64(l))
		}
	}
	if len(m.Badges) > 0 {
		for k, v := range m.Badges {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovCertid(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovCertid(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovCertid(uint64(mapEntrySize))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovCertid(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovCertid(uint64(l))
	if m.Verified {
		n += 3
	}
	if m.IsActive {
		n += 3
	}
	if m.VerificationLevel != 0 {
		n += 2 + sovCertid(uint64(m.VerificationLevel))
	}
	return n
}

func (m *Badge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.AwardedAt)
	n += 1 + l + sovCertid(uint64(l))
	l = len(m.AwardedBy)
	if l > 0 {
		n += 1 + l + sovCertid(uint64(l))
	}
	if m.IsRevoked {
		n += 2
	}
	if m.RevokedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt)
		n += 1 + l + sovCertid(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxUsernameLength != 0 {
		n += 1 + sovCertid(uint64(m.MaxUsernameLength))
	}
	if m.MaxDisplayNameLength != 0 {
		n += 1 + sovCertid(uint64(m.MaxDisplayNameLength))
	}
	if m.MaxBioLength != 0 {
		n += 1 + sovCertid(uint64(m.MaxBioLength))
	}
	if m.MaxCredentials != 0 {
		n += 1 + sovCertid(uint64(m.MaxCredentials))
	}
	l = m.RegistrationFee.Size()
	n += 1 + l + sovCertid(uint64(l))
	return n
}

func sovCertid(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCertid(x uint64) (n int) {
	return sovCertid(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CertID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Handle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvatarCID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvatarCID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataURI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataURI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityType", wireType)
			}
			m.EntityType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EntityType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustScore", wireType)
			}
			m.TrustScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocialLinks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SocialLinks == nil {
				m.SocialLinks = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCertid
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCertid
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCertid
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCertid
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCertid
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCertid
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthCertid
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCertid(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthCertid
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.SocialLinks[mapkey] = mapvalue
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credentials", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Credentials = append(m.Credentials, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Badges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Badges == nil {
				m.Badges = make(map[string]*Badge)
			}
			var mapkey string
			var mapvalue *Badge
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCertid
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCertid
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCertid
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCertid
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCertid
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthCertid
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthCertid
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Badge{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCertid(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthCertid
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Badges[mapkey] = mapvalue
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationLevel", wireType)
			}
			m.VerificationLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerificationLevel |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCertid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Badge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Badge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Badge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AwardedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.AwardedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AwardedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AwardedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRevoked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRevoked = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RevokedAt == nil {
				m.RevokedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.RevokedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCertid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCertid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxUsernameLength", wireType)
			}
			m.MaxUsernameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxUsernameLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDisplayNameLength", wireType)
			}
			m.MaxDisplayNameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDisplayNameLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBioLength", wireType)
			}
			m.MaxBioLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBioLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCredentials", wireType)
			}
			m.MaxCredentials = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCredentials |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCertid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCertid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegistrationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCertid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCertid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCertid(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCertid
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCertid
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCertid
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCertid
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCertid
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCertid        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCertid          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCertid = fmt.Errorf("proto: unexpected end of group")
)
